#version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: subanalytics-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: subanalytics-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  flask:
    build: ./flask-backend
    container_name: subanalytics-flask
    ports:
      - "5001:5001"
    env_file:
      - ./flask-backend/.env
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: subanalytics-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
      - flask

volumes:
  mongo_data:

