apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics
        image: tush1809/analytics:latest
        ports:
        - containerPort: 8000
        # Liveness probe: checks if container is alive, restarts if failing
        livenessProbe:
          httpGet:
            path: /health        # replace with your health endpoint
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        # Readiness probe: ensures container only receives traffic when healthy
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 8000
  type: ClusterIP

