apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics
        image: tush1809/analytics:latest
        ports:
        - containerPort: 8000   # match actual port inside container
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service   # fixed selector
  ports:
    - protocol: TCP
      port: 5002              # cluster port
      targetPort: 8000        # maps to containerPort
  type: ClusterIP

