apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  namespace: analytics
spec:
  selector:
    app: user-auth-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP


